CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       account_non_locked BOOLEAN NOT NULL,
                       address VARCHAR(255) NOT NULL,
                       created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
                       dob DATE NOT NULL,
                       email VARCHAR(255) NOT NULL,
                       failed_login_attempts INTEGER NOT NULL,
                       full_name VARCHAR(255) NOT NULL,
                       password VARCHAR(255) NOT NULL,
                       last_login TIMESTAMP(6) WITHOUT TIME ZONE,
                       password_reset_token VARCHAR(255),
                       phone_number VARCHAR(255) NOT NULL,
                       status VARCHAR(255) NOT NULL,
                       two_factor_auth_enabled BOOLEAN NOT NULL,
                       updated_at TIMESTAMP(6) WITHOUT TIME ZONE,

                       CONSTRAINT users_pkey PRIMARY KEY (id),
                       CONSTRAINT users_email_unique UNIQUE (email),
                       CONSTRAINT users_phone_number_unique UNIQUE (phone_number),
                       CONSTRAINT users_status_check
                           CHECK (status IN ('ACTIVE', 'SUSPENDED', 'CLOSED'))
);


CREATE TABLE bank_accounts (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                               account_nickname VARCHAR(20),
                               account_number VARCHAR(20) NOT NULL,
                               balance NUMERIC(19,4) NOT NULL,
                               created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
                               minimum_balance NUMERIC(38,2) NOT NULL,
                               overdraft_limit NUMERIC(38,2) NOT NULL,
                               status VARCHAR(255) NOT NULL,
                               type VARCHAR(255) NOT NULL,
                               updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
                               user_id BIGINT NOT NULL,

                               CONSTRAINT bank_accounts_pkey PRIMARY KEY (id),
                               CONSTRAINT bank_accounts_account_number_unique UNIQUE (account_number),

                               CONSTRAINT bank_accounts_status_check
                                   CHECK (status IN ('ACTIVE', 'FROZEN', 'CLOSED')),

                               CONSTRAINT bank_accounts_type_check
                                   CHECK (type IN ('CHECKING', 'SAVINGS', 'CREDIT')),

                               CONSTRAINT bank_accounts_user_fk
                                   FOREIGN KEY (user_id) REFERENCES users(id)
);


CREATE TABLE kyc_profile (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                             document_number_encrypted VARCHAR(255) NOT NULL,
                             document_type VARCHAR(255) NOT NULL,
                             last_verified_on DATE,
                             ssn_encrypted VARCHAR(255) NOT NULL,
                             status VARCHAR(255) NOT NULL,
                             status_changed_on DATE,
                             user_id BIGINT NOT NULL,

                             CONSTRAINT kyc_profile_pkey PRIMARY KEY (id),
                             CONSTRAINT kyc_profile_user_unique UNIQUE (user_id),

                             CONSTRAINT kyc_profile_status_check
                                 CHECK (status IN (
                                                   'UNVERIFIED',
                                                   'VERIFIED',
                                                   'PENDING_REVIEW',
                                                   'DENIED'
                                     )),

                             CONSTRAINT kyc_profile_user_fk
                                 FOREIGN KEY (user_id) REFERENCES users(id)
);


CREATE TABLE transactions (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                              amount NUMERIC(38,2) NOT NULL,
                              description VARCHAR(255),
                              destination_number VARCHAR(20),
                              status VARCHAR(255) NOT NULL,
                              "timestamp" TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
                              type VARCHAR(255) NOT NULL,
                              account_id BIGINT NOT NULL,

                              CONSTRAINT transactions_pkey PRIMARY KEY (id),

                              CONSTRAINT transactions_status_check
                                  CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),

                              CONSTRAINT transactions_type_check
                                  CHECK (type IN (
                                                  'DEPOSIT',
                                                  'WITHDRAWAL',
                                                  'TRANSFER_IN',
                                                  'TRANSFER_OUT'
                                      )),

                              CONSTRAINT transactions_account_fk
                                  FOREIGN KEY (account_id) REFERENCES bank_accounts(id)
);


CREATE TABLE user_roles (
                            user_id BIGINT NOT NULL,
                            roles VARCHAR(255) NOT NULL,

                            CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, roles),

                            CONSTRAINT user_roles_roles_check
                                CHECK (roles IN ('ADMIN', 'CUSTOMER', 'TELLER')),

                            CONSTRAINT user_roles_user_fk
                                FOREIGN KEY (user_id) REFERENCES users(id)
);