spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://localhost:5432/banking_app
spring.datasource.username=cake
spring.datasource.password=dZ>4oF!L72nMp}2

app.encryption.secret=12345678901234567890123456789012

# must be <= 32 characters
jwt.secret=superSecretKeyThatIsExactly32Chars!!

# expiration time in ms (1 hour)
jwt.expiration=3600000

