spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF

spring.jpa.hibernate.ddl-auto=validate

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

app.encryption.secret=${AES_SECRET}

# must be <= 32 characters
jwt.secret=${JWT_SECRET}

# expiration time in ms
jwt.expiration=${JWT_EXPIRATION}